import itemTypes from "@/utils/itemTypes";
import Head from "next/head";
import { DndProvider, useDrag } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";
import Column2 from "./Column2";
import Column1 from "./Columns1";
import Movable from "./MovableCom";

export default function Home() {
  return (
    <>
      <Head>
        <title>Drag & drop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DndProvider backend={HTML5Backend}>
        <div>
          <h2 className="font-[700] text-center text-2xl border-b pb-2">
            Drag and Drop
          </h2>
          <div className="flex justify-between list-none">
            <Column1 />
            <Column2 />
          </div>
        </div>
      </DndProvider>
    </>
  );
}
