import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Drag & drop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
      <h2 className='font-[700] text-center text-2xl border-b pb-2'>Drag and Drop</h2>
      <div className='list-none flex justify-between '>
        <div className='border p-3 m-3 basis-[300px] rounded-sm'>
          <h2 className='font-[600] text-xl border-b'>To do</h2>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
        </div>
        <div className='border p-3 m-3 basis-[300px] rounded-sm'>
          <h2 className='font-[600] text-xl border-b'>To do</h2>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
        </div>
        <div className='border p-3 m-3 basis-[300px] rounded-sm'>
          <h2 className='font-[600] text-xl border-b'>To do</h2>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
          <li className='border rounded-md p-3 my-1'>Option</li>
        </div>
      </div>
     </div>
    </>
  )
}
